# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from crop_face import crop_face_many_folders, crop_face_one_folder

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 489)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dialog_tool2 = QtWidgets.QTabWidget(self.centralwidget)
        self.dialog_tool2.setGeometry(QtCore.QRect(-10, 0, 791, 461))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dialog_tool2.setFont(font)
        self.dialog_tool2.setObjectName("dialog_tool2")
        self.Tool1 = QtWidgets.QWidget()
        self.Tool1.setObjectName("Tool1")
        self.label = QtWidgets.QLabel(self.Tool1)
        self.label.setGeometry(QtCore.QRect(40, 170, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.folder_input_path_tool1 = QtWidgets.QLineEdit(self.Tool1)
        self.folder_input_path_tool1.setGeometry(QtCore.QRect(320, 170, 321, 31))
        self.folder_input_path_tool1.setObjectName("folder_input_path_tool1")
        self.button_choose1_tool1 = QtWidgets.QPushButton(self.Tool1)
        self.button_choose1_tool1.setGeometry(QtCore.QRect(660, 170, 93, 28))
        self.button_choose1_tool1.setObjectName("button_choose1_tool1")
        self.button_choose1_tool1.clicked.connect(self.chooseFolderInput1)      #event
        self.label_3 = QtWidgets.QLabel(self.Tool1)
        self.label_3.setGeometry(QtCore.QRect(40, 240, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.folder_output_path_tool1 = QtWidgets.QLineEdit(self.Tool1)
        self.folder_output_path_tool1.setGeometry(QtCore.QRect(320, 240, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.folder_output_path_tool1.setFont(font)
        self.folder_output_path_tool1.setText("")
        self.folder_output_path_tool1.setPlaceholderText("")
        self.folder_output_path_tool1.setObjectName("folder_output_path_tool1")
        self.button_choose2_tool1 = QtWidgets.QPushButton(self.Tool1)
        self.button_choose2_tool1.setGeometry(QtCore.QRect(660, 240, 93, 28))
        self.button_choose2_tool1.setObjectName("button_choose2_tool1")
        self.button_choose2_tool1.clicked.connect(self.chooseFolderOutput1)     #event
        self.button_crop_tool1 = QtWidgets.QPushButton(self.Tool1)
        self.button_crop_tool1.setGeometry(QtCore.QRect(610, 310, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_crop_tool1.setFont(font)
        self.button_crop_tool1.setObjectName("button_crop_tool1")
        self.button_crop_tool1.clicked.connect(self.cropTool1)          #event
        self.label_2 = QtWidgets.QLabel(self.Tool1)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.Tool1)
        self.textBrowser.setGeometry(QtCore.QRect(430, 30, 321, 91))
        self.textBrowser.setObjectName("textBrowser")
        self.label_4 = QtWidgets.QLabel(self.Tool1)
        self.label_4.setGeometry(QtCore.QRect(40, 310, 541, 41))
        self.label_4.setObjectName("label_4")
        self.dialog_tool2.addTab(self.Tool1, "")
        self.Tool2 = QtWidgets.QWidget()
        self.Tool2.setObjectName("Tool2")
        self.label_7 = QtWidgets.QLabel(self.Tool2)
        self.label_7.setGeometry(QtCore.QRect(40, 40, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.Tool2)
        self.label_8.setGeometry(QtCore.QRect(40, 150, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.folder_input_path_tool2 = QtWidgets.QLineEdit(self.Tool2)
        self.folder_input_path_tool2.setGeometry(QtCore.QRect(340, 150, 301, 31))
        self.folder_input_path_tool2.setObjectName("folder_input_path_tool2")
        self.label_9 = QtWidgets.QLabel(self.Tool2)
        self.label_9.setGeometry(QtCore.QRect(40, 220, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.folder_output_path_tool2 = QtWidgets.QLineEdit(self.Tool2)
        self.folder_output_path_tool2.setGeometry(QtCore.QRect(340, 220, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.folder_output_path_tool2.setFont(font)
        self.folder_output_path_tool2.setText("")
        self.folder_output_path_tool2.setPlaceholderText("")
        self.folder_output_path_tool2.setObjectName("folder_output_path_tool2")
        self.button_choose1_tool2 = QtWidgets.QPushButton(self.Tool2)
        self.button_choose1_tool2.setGeometry(QtCore.QRect(660, 150, 93, 28))
        self.button_choose1_tool2.setObjectName("button_choose1_tool2")
        self.button_choose1_tool2.clicked.connect(self.chooseFolderInput2)      #event
        self.button_choose2_tool2 = QtWidgets.QPushButton(self.Tool2)
        self.button_choose2_tool2.setGeometry(QtCore.QRect(660, 220, 93, 28))
        self.button_choose2_tool2.setObjectName("button_choose2_tool2")
        self.button_choose2_tool2.clicked.connect(self.chooseFolderOutput2)     #event
        self.button_crop_tool2 = QtWidgets.QPushButton(self.Tool2)
        self.button_crop_tool2.setGeometry(QtCore.QRect(610, 310, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_crop_tool2.setFont(font)
        self.button_crop_tool2.setObjectName("button_crop_tool2")
        self.button_crop_tool2.clicked.connect(self.cropTool2)      #event
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.Tool2)
        self.textBrowser_2.setGeometry(QtCore.QRect(440, 40, 311, 61))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_5 = QtWidgets.QLabel(self.Tool2)
        self.label_5.setGeometry(QtCore.QRect(40, 310, 541, 41))
        self.label_5.setObjectName("label_5")
        self.dialog_tool2.addTab(self.Tool2, "")
        self.Guideline = QtWidgets.QWidget()
        self.Guideline.setObjectName("Guideline")
        self.label_6 = QtWidgets.QLabel(self.Guideline)
        self.label_6.setGeometry(QtCore.QRect(60, 20, 421, 91))
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.Guideline)
        self.label_10.setGeometry(QtCore.QRect(60, 130, 421, 91))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.Guideline)
        self.label_11.setGeometry(QtCore.QRect(60, 250, 451, 91))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.Guideline)
        self.label_12.setGeometry(QtCore.QRect(580, 50, 55, 16))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.Guideline)
        self.label_13.setGeometry(QtCore.QRect(530, 10, 201, 111))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.Guideline)
        self.label_14.setGeometry(QtCore.QRect(530, 130, 211, 111))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.Guideline)
        self.label_15.setGeometry(QtCore.QRect(520, 240, 251, 161))
        self.label_15.setObjectName("label_15")
        self.dialog_tool2.addTab(self.Guideline, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.dialog_tool2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Choose folder data input"))
        self.button_choose1_tool1.setText(_translate("MainWindow", "Browse"))
        self.label_3.setText(_translate("MainWindow", "Choose folder data output "))
        self.button_choose2_tool1.setText(_translate("MainWindow", "Browse"))
        self.button_crop_tool1.setText(_translate("MainWindow", "Crop"))
        self.label_2.setText(_translate("MainWindow", "Crop Face From Image "))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Use for folder data contains different portrait image folders, with that image folder name is name of persons.</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><a name=\"tw-target-text\"/><span style=\" font-family:\'inherit\'; font-size:9pt; color:#202124;\">Y</span><span style=\" font-family:\'inherit\'; font-size:9pt; color:#202124;\">ou can open the output folder to see the result after clicking the &quot;Cut&quot; button.</span></p></body></html>"))
        self.dialog_tool2.setTabText(self.dialog_tool2.indexOf(self.Tool1), _translate("MainWindow", "Tool1"))
        self.label_7.setText(_translate("MainWindow", "Crop Face From Image "))
        self.label_8.setText(_translate("MainWindow", "Choose folder image input"))
        self.label_9.setText(_translate("MainWindow", "Choose folder image output "))
        self.button_choose1_tool2.setText(_translate("MainWindow", "Browse"))
        self.button_choose2_tool2.setText(_translate("MainWindow", "Browse"))
        self.button_crop_tool2.setText(_translate("MainWindow", "Crop"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Use for folder image contains different portrait images of persons.</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><a name=\"tw-target-text\"/><span style=\" font-family:\'inherit\'; font-size:9pt; color:#202124;\">Y</span><span style=\" font-family:\'inherit\'; font-size:9pt; color:#202124;\">ou can open the output folder to see the result after clicking the &quot;Cut&quot; button.</span></p></body></html>"))
        self.dialog_tool2.setTabText(self.dialog_tool2.indexOf(self.Tool2), _translate("MainWindow", "Tool2"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Tool1:</span><span style=\" font-size:11pt;\"> Use for folder data contains different portrait <br/>image folders, with that image folder name is name<br/>of persons. </span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Tool2: </span><span style=\" font-size:11pt;\">Use for folder image contains different portrait <br/>images of persons.</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Successful message: </span><span style=\" font-size:11pt;\">After some time of processing,<br/>display a message when it\'s done. The images have<br/>been cropped successfully.</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><img src=\".\images\pic1.jpg\"/></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><img src=\".\images\pic2.jpg\"/></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><img src=\".\images\pic3.jpg\"/></p></body></html>"))
        self.dialog_tool2.setTabText(self.dialog_tool2.indexOf(self.Guideline), _translate("MainWindow", "Guideline"))

#function for events

    def chooseFolderInput1(self):
        folder_path = QtWidgets.QFileDialog.getExistingDirectory(None, "Select choose folder")
        self.folder_input_path_tool1.setText(folder_path)
    
    def chooseFolderOutput1(self):
        folder_path = QtWidgets.QFileDialog.getExistingDirectory(None, "Select choose folder")
        self.folder_output_path_tool1.setText(folder_path)
    
    def chooseFolderInput2(self):
        folder_path = QtWidgets.QFileDialog.getExistingDirectory(None, "Select choose folder")
        self.folder_input_path_tool2.setText(folder_path)
    
    def chooseFolderOutput2(self):
        folder_path = QtWidgets.QFileDialog.getExistingDirectory(None, "Select choose folder")
        self.folder_output_path_tool2.setText(folder_path)
       
    def cropTool1(self):
        ans = QtWidgets.QMessageBox.question(None, 'Confirm', "Are you crop image?", QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No | QtWidgets.QMessageBox.Cancel, QtWidgets.QMessageBox.Cancel)
        if ans == QtWidgets.QMessageBox.Yes:
            folder_data_in = self.folder_input_path_tool1.text()
            folder_data_out = self.folder_output_path_tool1.text()
            if folder_data_in=="" or folder_data_out=="":
                QtWidgets.QMessageBox.about(None,"Error","Empty folder path")
            else: 
                crop_face_many_folders(folder_data_in,folder_data_out)            
                QtWidgets.QMessageBox.about(None,"Successful","Cropped images successful!")
    
    def cropTool2(self):
        ans = QtWidgets.QMessageBox.question(None, 'Confirm', "Are you crop image?", QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No | QtWidgets.QMessageBox.Cancel, QtWidgets.QMessageBox.Cancel)
        if ans == QtWidgets.QMessageBox.Yes:
            folder_image_in = self.folder_input_path_tool2.text()
            folder_image_out = self.folder_output_path_tool2.text()
            if folder_image_in=="" or folder_image_out=="":
                QtWidgets.QMessageBox.about(None,"Error","Empty folder path")
            else: 
                crop_face_one_folder(folder_image_in,folder_image_out) 
                QtWidgets.QMessageBox.about(None,"Successful","Cropped images successful!")  
                      
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
